### ISSUE TITLE
Initial recurring other than Custom - switch to custom

### ISSUE THREAD

**Issue by jegade** [itnode/rrule-editor#1]
If a initial recurring or first selected recurring is switch to custom, these case was not reflected inside the modal form

1. Select weekly recurring or preset by hidden field
![selection_213](https://user-images.githubusercontent.com/97133/33178121-46e25152-d065-11e7-992d-f656612f2dc9.png)

2. Select custom recurring 
![selection_215](https://user-images.githubusercontent.com/97133/33178158-6c0c540a-d065-11e7-81a9-1bec9a222dda.png)

3. Here i expected that weekly was selected and not daily

**Comment by rabeesh** [comment]
This feature is added in https://github.com/itnode/rrule-editor/commit/9a6303c0cbcab46a4615dbb199f6414be920b95b
