### ISSUE TITLE
Custom Daily should result in Daily rule

### ISSUE THREAD

**Issue by jegade** [itnode/rrule-editor#2]
If a custom basic daily rule selected, then the select should be resetted to daily 

"Custom" Daily, without further options
![selection_215](https://user-images.githubusercontent.com/97133/33178258-db6581dc-d065-11e7-8b3e-fe6e18333cc0.png)

Generates this rule 
`FREQ=DAILY;DTSTART=20171123T000000Z;BYDAY=MO,TU,WE,TH,FR,SA,SU` 

But should only simple Basic Rule
`FREQ=DAILY;DTSTART=20171123T000000Z`

And select should be resetted to Daily instead of Custom

**Comment by rabeesh** [comment]
FIxed in https://github.com/itnode/rrule-editor/commit/9a6303c0cbcab46a4615dbb199f6414be920b95b
