### ISSUE TITLE
Firefox 57 did not work - no select possible 

### ISSUE THREAD

**Issue by jegade** [itnode/rrule-editor#4]
**TypeError: this.$.reccurend.nextSibling.style is undefined**

toggleModalForm http://192.168.178.2:8081/components/rrule-editor/rrule-editor.html.js:183:11
openModalAndPopulate http://192.168.178.2:8081/components/rrule-editor/rrule-editor.html.js:99:11
initSlotEvents/  http://192.168.178.2:8081/components/rrule-editor/rrule-editor.html.js:114:13
patch-events.js:360:8 receiveMessage resource://gre/modules/SelectContentHelper.jsm:299:11

**Comment by jegade** [comment]
![selection_217](https://user-images.githubusercontent.com/97133/33268468-a8826710-d37d-11e7-8209-9e5f1c10c60e.png)

**Comment by rabeesh** [comment]
Firefox not supporting `after` method, changed into `parentNode.insertBefore`

Fixed in https://github.com/itnode/rrule-editor/commit/bb9409a006ab8a4098eb75f8576212489a806296
