### ISSUE TITLE
Dependency Management pf-calendar ...

### ISSUE THREAD

**Issue by jegade** [itnode/rrule-editor#5]
Please validate the required modules 

**Why is calendar pf-calendar required?** 
`<link rel="import" href="../pf-calendar/pf-calendar.html">`

**Why is firebase required? Is this a dependency of pf-calendar** 
firebase-app.html
firebase-auth.html
firebase-document.html
firebase-query.html
firebase-messaging.html
firebase-storage-multiupload.html
firebase-storage-upload-task.html
firebase-storage-ref.html
common-worker.html
firebase-app-script.html
firebase-database-script.html
firebase-auth-script.html
firebase-storage-script.html
firebase-messaging-script.html
firebase-common-behavior.html
firebase-database-behavior.html
firebase-storage-behavior.html
firebase-app.js
firebase-database.js
firebase-auth.js
firebase-storage.js
firebase-messaging.js

**Comment by rabeesh** [comment]
Fixed in https://github.com/itnode/rrule-editor/commit/d82ea3d5d0a8b031a05d230565d1853819260dfa
